#!/bin/sh; C:/Users/s.leven/AppData/Local/GitHubDesktop/app-1.6.2/resources/app/git/usr/bin/sh.exe
#
# An example hook script for version generation after each commit.
#
# To enable this hook, rename this file to "post-merge".
#
# Note: no file extension. Requires Python 3.x.

python version.py
echo "Version information generated after merge"